baseURL = "https://ChrisPluto.github.io/dca-blog/"
languageCode = "zh-cn"
title = "小李飞刀的投资记录"
disableKinds = ["taxonomy", "term"]

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
